
[tool.uv.workspace]
members = [
  "src/backend/langflow*",
]
[tool.uv.sources]
langflow-base = { workspace = true }
langflow = { workspace = true }

[tool.uv]
dev-dependencies = [
  "types-redis >=4.6.0.5,<5",
  "ipykernel >=6.29.0,<7",
  "mypy >=1.11.0,<2",
  "ruff >=0.4.5,<1",
  "httpx",
  "pytest >=8.2.0,<9",
  "types-requests >=2.32.0,<3",
  "requests >=2.32.0,<3",
  "pytest-cov >=5.0.0,<6",
  "pandas-stubs >=2.1.4.231227,<3",
  "types-pillow >=10.2.0.20240213,<11",
  "types-pyyaml >=6.0.12.8,<7",
  "types-python-jose >=3.3.4.8,<4",
  "types-passlib >=1.7.7.13,<2",
  "locust >=2.23.1,<3",
  "pytest-mock >=3.14.0,<4",
  "pytest-xdist >=3.6.0,<4",
  "types-pywin32 >=306.0.0.4,<307",
  "types-google-cloud-ndb >=2.2.0.0,<3",
  "pytest-sugar >=1.0.0,<2",
  "respx >=0.21.1,<1",
  "pytest-instafail >=0.5.0,<1",
  "pytest-asyncio >=0.23.0,<1",
  "pytest-profiling >=1.7.0,<2",
  "pre-commit >=3.7.0,<4",
  "vulture >=2.11,<3",
  "dictdiffer >=0.9.0,<1",
  "pytest-split >=0.9.0,<1",
  "pytest-flakefinder >=1.1.0,<2"
]

[tool.codespell]
skip = '.git,*.pdf,*.svg,*.pdf,*.yaml,*.ipynb,poetry.lock,*.min.js,*.css,package-lock.json,*.trig.,**/node_modules/**,./stuff/*,*.csv'
# Ignore latin etc
ignore-regex = '.*(Stati Uniti|Tense=Pres).*'


[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests", "integration"]
console_output_style = "progress"
filterwarnings = ["ignore::DeprecationWarning", "ignore::ResourceWarning"]
log_cli = true
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
markers = ["async_test", "api_key_required"]


[tool.coverage.run]
command_line = """
    -m pytest --ignore=tests/integration
    --cov --cov-report=term --cov-report=html
    --instafail -ra -n auto -m "not api_key_required"
"""
source = ["src/backend/base/langflow/"]
omit = ["*/alembic/*", "tests/*", "*/__init__.py"]


[tool.coverage.report]
sort = "Stmts"
skip_empty = true
show_missing = false
ignore_errors = true


[tool.coverage.html]
directory = "coverage"


[tool.ruff]
exclude = ["src/backend/langflow/alembic/*"]
line-length = 120

[tool.mypy]
plugins = ["pydantic.mypy"]
follow_imports = "skip"
disable_error_code = ["type-var"]
namespace_packages = true
mypy_path = "langflow"
ignore_missing_imports = true
